export const RULE_TITLE_RU: Record<string, string> = {
  "ACTIVE_CAMPAIGN_WITHOUT_ACTIVE_GROUPS": "Активная кампания без рабочих групп",
  "ACTIVE_GROUP_WITHOUT_ACTIVE_ADS": "Активная группа без активных объявлений",
  "ACTIVE_GROUP_WITHOUT_TARGETING": "Активная группа без активных фраз или таргетингов",
  "GROUP_ALL_ADS_REJECTED": "Все объявления в группе отклонены модерацией",
  "ACTIVE_AD_REJECTED_OR_RESTRICTED": "Объявление отклонено или ограничено модерацией",
  "DUPLICATE_KEYWORDS_IN_GROUP": "Дубликаты ключевых фраз в одной группе",
  "DUPLICATE_KEYWORDS_WITH_OVERLAP": "Дубликаты ключевых фраз в кампании или аккаунте с пересечением настроек",
  "KEYWORD_CONFLICTS_WITH_GROUP_NEGATIVES": "Ключевая фраза пересечена минус-словом группы",
  "KEYWORD_CONFLICTS_WITH_CAMPAIGN_NEGATIVES": "Ключевая фраза пересечена минус-словом кампании",
  "GROUP_KEYWORD_OVERLAP": "Пересечение групп по одинаковым или близким ключам",
  "MISSING_CROSS_NEGATIVES": "Отсутствие кросс-минусовки между группами",
  "DUPLICATE_ADS": "Дубликаты объявлений",
  "DUPLICATE_SITELINKS": "Дубликаты быстрых ссылок",
  "MISSING_REQUIRED_EXTENSIONS": "Объявление без обязательных или ожидаемых дополнений",
  "EXPIRED_DATE_IN_AD_TEXT": "Неактуальная дата в тексте объявления",
  "PAST_YEAR_IN_TEXT": "Упоминание прошлого года в тексте",
  "EXPIRED_DATE_IN_EXTENSIONS": "Неактуальная дата в быстрых ссылках или уточнениях",
  "UNRESOLVED_PLACEHOLDER_IN_TEXT": "Незаполненные шаблоны или плейсхолдеры в тексте",
  "UNRESOLVED_PLACEHOLDER_IN_URL": "Незаполненные шаблоны или макросы в URL",
  "GEO_TEXT_TARGETING_MISMATCH": "Гео в тексте не совпадает с геотаргетингом",
  "CAMPAIGN_SELF_COMPETITION_BY_GEO_AND_SEMANTICS": "Активные кампании с пересекающимся гео и одинаковой семантикой",
  "CAMPAIGN_GEO_OVERLAPS_CAMPAIGN_NEGATIVES": "Настройки гео пересечены с минус-словом кампании",
  "CONVERSION_STRATEGY_WITHOUT_METRIKA": "Стратегия по конверсиям без счетчика Метрики",
  "CONVERSION_STRATEGY_WITHOUT_GOAL": "Стратегия по конверсиям без цели",
  "CONVERSION_STRATEGY_WITH_UNAVAILABLE_GOAL": "Используется удаленная или недоступная цель",
  "CONVERSION_STRATEGY_WITHOUT_LEARNING_DATA": "Стратегия по конверсиям без статистики для обучения",
  "CAMPAIGN_CHRONIC_BUDGET_LIMIT": "Кампания системно упирается в бюджет",
  "CAMPAIGN_WITHOUT_METRIKA_COUNTER": "Яндекс Метрика не подключена в настройках кампании",
  "CAMPAIGN_WITHOUT_METRIKA_GOALS": "Цели Яндекс Метрики не добавлены в кампанию",
  "INVALID_URL_SYNTAX": "Некорректный синтаксис URL",
  "FINAL_URL_HTTP_ERROR": "Ссылка ведет на 4xx или 5xx",
  "FINAL_URL_DNS_TIMEOUT_CONNECTION_ERROR": "Ошибка DNS, таймаут или сбой соединения",
  "FINAL_URL_SSL_TLS_ERROR": "Ошибка SSL/TLS (сертификат или шифрование)",
  "REDIRECT_LOOP": "Зацикливание редиректов",
  "REDIRECT_CHAIN_TOO_LONG": "Слишком длинная цепочка редиректов",
  "FINAL_DOMAIN_DIFFERS_AFTER_REDIRECT": "Финальный домен после редиректа отличается от исходного",
  "HTTP_USED_INSTEAD_OF_HTTPS": "Используется HTTP вместо HTTPS",
  "BROKEN_SITELINK_URL": "Битые быстрые ссылки",
  "MISSING_REQUIRED_UTM": "Отсутствуют UTM-метки там, где они обязательны",
  "INVALID_UTM": "Некорректные UTM-метки",
  "INCONSISTENT_UTM_PATTERN": "Непоследовательная разметка UTM в аккаунте",
  "MAIN_AND_SITELINK_DOMAINS_MISMATCH": "URL в объявлении и быстрых ссылках ведут на разные домены",
  "EMPTY_OR_TECHNICAL_URL_PARAMS": "Пустые или технические параметры в URL",
};

export function ruleTitleRu(code: string, fallback: string): string {
  return RULE_TITLE_RU[code] ?? fallback;
}
